# Generated by Django 4.2.5 on 2023-10-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_avatarclubes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubes',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='clubes_avatares/'),
        ),
    ]
