# Generated by Django 4.2.5 on 2023-10-08 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_clubes_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubes',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
